//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8762
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.8762 版自动生成。
// 
#pragma warning disable 1591

namespace agvtxws.wms2agv {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AGVSrvSoap", Namespace="http://tempuri.org/")]
    public partial class AGVSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecevieWMStasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback PalletOutReadyOperationCompleted;
        
        private System.Threading.SendOrPostCallback testWMScallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AGVSrv() {
            this.Url = global::agvtxws.Properties.Settings.Default.agvtxws_wms2agv_AGVSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecevieWMStasksCompletedEventHandler RecevieWMStasksCompleted;
        
        /// <remarks/>
        public event PalletOutReadyCompletedEventHandler PalletOutReadyCompleted;
        
        /// <remarks/>
        public event testWMScallCompletedEventHandler testWMScallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecevieWMStasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AGVfeedBack RecevieWMStasks(string taskID, WMS_PartsDeliver[] partDatas) {
            object[] results = this.Invoke("RecevieWMStasks", new object[] {
                        taskID,
                        partDatas});
            return ((AGVfeedBack)(results[0]));
        }
        
        /// <remarks/>
        public void RecevieWMStasksAsync(string taskID, WMS_PartsDeliver[] partDatas) {
            this.RecevieWMStasksAsync(taskID, partDatas, null);
        }
        
        /// <remarks/>
        public void RecevieWMStasksAsync(string taskID, WMS_PartsDeliver[] partDatas, object userState) {
            if ((this.RecevieWMStasksOperationCompleted == null)) {
                this.RecevieWMStasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecevieWMStasksOperationCompleted);
            }
            this.InvokeAsync("RecevieWMStasks", new object[] {
                        taskID,
                        partDatas}, this.RecevieWMStasksOperationCompleted, userState);
        }
        
        private void OnRecevieWMStasksOperationCompleted(object arg) {
            if ((this.RecevieWMStasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecevieWMStasksCompleted(this, new RecevieWMStasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PalletOutReady", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PalletOutReady(string pallet, string portNo) {
            object[] results = this.Invoke("PalletOutReady", new object[] {
                        pallet,
                        portNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PalletOutReadyAsync(string pallet, string portNo) {
            this.PalletOutReadyAsync(pallet, portNo, null);
        }
        
        /// <remarks/>
        public void PalletOutReadyAsync(string pallet, string portNo, object userState) {
            if ((this.PalletOutReadyOperationCompleted == null)) {
                this.PalletOutReadyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPalletOutReadyOperationCompleted);
            }
            this.InvokeAsync("PalletOutReady", new object[] {
                        pallet,
                        portNo}, this.PalletOutReadyOperationCompleted, userState);
        }
        
        private void OnPalletOutReadyOperationCompleted(object arg) {
            if ((this.PalletOutReadyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PalletOutReadyCompleted(this, new PalletOutReadyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/testWMScall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string testWMScall() {
            object[] results = this.Invoke("testWMScall", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testWMScallAsync() {
            this.testWMScallAsync(null);
        }
        
        /// <remarks/>
        public void testWMScallAsync(object userState) {
            if ((this.testWMScallOperationCompleted == null)) {
                this.testWMScallOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestWMScallOperationCompleted);
            }
            this.InvokeAsync("testWMScall", new object[0], this.testWMScallOperationCompleted, userState);
        }
        
        private void OntestWMScallOperationCompleted(object arg) {
            if ((this.testWMScallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testWMScallCompleted(this, new testWMScallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WMS_PartsDeliver {
        
        private string eRPOrderIDField;
        
        private string transactionIDField;
        
        private int distributionModeField;
        
        private string organizationCodeField;
        
        private string warehouseField;
        
        private string sterrooutexitexitcodeField;
        
        private string workCenterCodeField;
        
        private int distributionPartyField;
        
        private string palletCodeField;
        
        private Material[] materialsField;
        
        /// <remarks/>
        public string ERPOrderID {
            get {
                return this.eRPOrderIDField;
            }
            set {
                this.eRPOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public int DistributionMode {
            get {
                return this.distributionModeField;
            }
            set {
                this.distributionModeField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
        
        /// <remarks/>
        public string Sterrooutexitexitcode {
            get {
                return this.sterrooutexitexitcodeField;
            }
            set {
                this.sterrooutexitexitcodeField = value;
            }
        }
        
        /// <remarks/>
        public string WorkCenterCode {
            get {
                return this.workCenterCodeField;
            }
            set {
                this.workCenterCodeField = value;
            }
        }
        
        /// <remarks/>
        public int DistributionParty {
            get {
                return this.distributionPartyField;
            }
            set {
                this.distributionPartyField = value;
            }
        }
        
        /// <remarks/>
        public string PalletCode {
            get {
                return this.palletCodeField;
            }
            set {
                this.palletCodeField = value;
            }
        }
        
        /// <remarks/>
        public Material[] Materials {
            get {
                return this.materialsField;
            }
            set {
                this.materialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Material {
        
        private string materialCodeField;
        
        private float quantityField;
        
        private int endFlagField;
        
        private string batchNumField;
        
        private string serialNumberField;
        
        private string vendorNumberField;
        
        private string vendorNameField;
        
        /// <remarks/>
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public float Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public int EndFlag {
            get {
                return this.endFlagField;
            }
            set {
                this.endFlagField = value;
            }
        }
        
        /// <remarks/>
        public string BatchNum {
            get {
                return this.batchNumField;
            }
            set {
                this.batchNumField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string VendorNumber {
            get {
                return this.vendorNumberField;
            }
            set {
                this.vendorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string VendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PartsDeliverRtn {
        
        private string eRPOrderIDField;
        
        private string palletCodeField;
        
        private string resultField;
        
        private string errCodeField;
        
        private string mSGField;
        
        /// <remarks/>
        public string ERPOrderID {
            get {
                return this.eRPOrderIDField;
            }
            set {
                this.eRPOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string PalletCode {
            get {
                return this.palletCodeField;
            }
            set {
                this.palletCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MSG {
            get {
                return this.mSGField;
            }
            set {
                this.mSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AGVfeedBack {
        
        private string idField;
        
        private PartsDeliverRtn[] palletResultField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PartsDeliverRtn[] PalletResult {
            get {
                return this.palletResultField;
            }
            set {
                this.palletResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void RecevieWMStasksCompletedEventHandler(object sender, RecevieWMStasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecevieWMStasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecevieWMStasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AGVfeedBack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AGVfeedBack)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PalletOutReadyCompletedEventHandler(object sender, PalletOutReadyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PalletOutReadyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PalletOutReadyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void testWMScallCompletedEventHandler(object sender, testWMScallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testWMScallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testWMScallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591