;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; FolderInfo.ini : Folder definitions for localization purposes
;;
;; Copyright © 2005-2006 OCP Software, Inc.
;;
;; All Rights Reserved.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[FolderInfo]
Order=18,5,19,1,6,7,8,10,9,2,3,15,16,4,17,11,12,13,14
01="\Program Files"
02="\Windows"
03="\Windows\Desktop"
04="\Windows\Startup"
05="\My Documents"
06="\Program Files\Accessories"
07="\Program Files\Communication"
08="\Program Files\Games"
09="\Program Files\Pocket Outlook"
10="\Program Files\Office"
11="\Windows\Start Menu\Programs"
12="\Windows\Start Menu\Programs\Accessories"
13="\Windows\Start Menu\Programs\Communication"
14="\Windows\Start Menu\Programs\Games"
15="\Windows\Fonts"
16="\Windows\Recent"
17="\Windows\Start Menu"
18="\<Default Volume>"
19="\Application Data"

[MacroExpansion]
01="%ProgramFiles%"
02="%Windows%"
03="%Desktop%"
04="%Startup%"
05="%MyDocuments%"
06="%ProgramFiles_Accessories%"
07="%ProgramFiles_Communication%"
08="%ProgramFiles_Games%"
09="%ProgramFiles_PocketOutlook%"
10="%ProgramFiles_Office%"
11="%StartMenu_Programs%"
12="%StartMenu_Programs_Accessories%"
13="%StartMenu_Programs_Communication%"
14="%StartMenu_Programs_Games%"
15="%Fonts%"
16="%Recent%"
17="%StartMenu%"
18="%DefaultVolume%"
19="%ApplicationData%"
